export type Rarity = "common" | "rare" | "epic" | "legendary" | "mythic";

export interface Champion {
  slug: string;
  name: string;
  title: string;
  rarity: Rarity;
  house: string;
  weapon: string;
  weaponClass: string;
  passive: { name: string; desc: string };
  ultimate: { name: string; desc: string };
  stats: { attack: number; defense: number; health: number; speed: number };
  lore: string;
  unlocked: boolean;
  art?: string;
}

export const champions: Champion[] = [
  {
    slug: "aeron-the-black",
    name: "Aeron the Black",
    title: "Warden of the Obsidian Coast",
    rarity: "legendary",
    house: "House Corvane",
    weapon: "Longsword",
    weaponClass: "Blade",
    passive: {
      name: "Raven's Eye",
      desc: "Aeron reads every feint before it lands, gaining bonus attack against foes who missed him last turn.",
    },
    ultimate: {
      name: "Blackwater Surge",
      desc: "A tide of obsidian-dark steel crashes over all enemies, dealing heavy damage that grows with each fallen ally avenged.",
    },
    stats: { attack: 3400, defense: 1350, health: 12500, speed: 430 },
    lore: "They say Aeron once out-negotiated a storm. The storm disputes this, but quietly, and from a respectful distance.",
    unlocked: true,
    art: "/game/champions/aeron-the-black.png",
  },
  {
    slug: "ser-willas",
    name: "Ser Willas",
    title: "The Unmoved",
    rarity: "rare",
    house: "House Frosthold",
    weapon: "Warhammer",
    weaponClass: "Bludgeon",
    passive: {
      name: "Frozen Footing",
      desc: "Ser Willas cannot be knocked back or slowed while above half health.",
    },
    ultimate: {
      name: "Shield Wall",
      desc: "Willas plants his hammer and raises an unbreakable barrier, absorbing all damage for his allies for two turns.",
    },
    stats: { attack: 1500, defense: 1400, health: 11000, speed: 320 },
    lore: "Willas has held three bridges, two gates, and one very awkward dinner conversation. He yielded none of them.",
    unlocked: true,
    art: "/game/champions/ser-willas.png",
  },
  {
    slug: "mira-stormborn",
    name: "Mira Stormborn",
    title: "Daughter of Thunder",
    rarity: "epic",
    house: "House Stormcrest",
    weapon: "Twin Blades",
    weaponClass: "Dual Blade",
    passive: {
      name: "Static Charge",
      desc: "Each strike builds a charge, and every third hit releases a bolt of lightning at a random foe.",
    },
    ultimate: {
      name: "Tempest",
      desc: "Mira becomes a whirlwind of steel and lightning, striking every enemy twice in a single breath.",
    },
    stats: { attack: 2700, defense: 850, health: 9200, speed: 495 },
    lore: "Born during the worst gale in a century, Mira considers calm weather a personal insult and fights like she is settling the score.",
    unlocked: true,
    art: "/game/champions/mira-stormborn.png",
  },
  {
    slug: "torvald-ironhand",
    name: "Torvald Ironhand",
    title: "The Anvil of the North",
    rarity: "epic",
    house: "House Frosthold",
    weapon: "Greataxe",
    weaponClass: "Axe",
    passive: {
      name: "Cold Forged",
      desc: "Torvald gains stacking defense each turn he takes damage without falling.",
    },
    ultimate: {
      name: "Ironhide",
      desc: "Torvald's skin hardens to living steel, halving all incoming damage and reflecting a portion back at attackers.",
    },
    stats: { attack: 2500, defense: 1450, health: 11800, speed: 330 },
    lore: "Torvald lost his hand to frostbite and replaced it with iron. Ask him which hand hits harder and he will happily demonstrate both.",
    unlocked: false,
    art: "/game/champions/torvald-ironhand.png",
  },
  {
    slug: "lady-ysolde",
    name: "Lady Ysolde",
    title: "The Gilded Thorn",
    rarity: "rare",
    house: "House Goldmane",
    weapon: "Rapier",
    weaponClass: "Blade",
    passive: {
      name: "Perfect Poise",
      desc: "Ysolde's precise footwork grants her a chance to dodge any single-target attack.",
    },
    ultimate: {
      name: "Riposte",
      desc: "Ysolde parries the next attack against her and answers with a flawless counter dealing triple damage.",
    },
    stats: { attack: 1700, defense: 700, health: 8000, speed: 460 },
    lore: "Ysolde duels the way she dances at court, beautifully, briefly, and always leaving her partner on the floor.",
    unlocked: false,
    art: "/game/champions/lady-ysolde.png",
  },
  {
    slug: "karn-the-reaver",
    name: "Karn the Reaver",
    title: "Terror of the Ember Coast",
    rarity: "epic",
    house: "House Emberfall",
    weapon: "Cleaver",
    weaponClass: "Blade",
    passive: {
      name: "Scent of Victory",
      desc: "Karn deals bonus damage to any enemy below half health.",
    },
    ultimate: {
      name: "Bloodlust",
      desc: "Karn enters a frenzy, attacking twice per turn and healing for a portion of all damage he deals.",
    },
    stats: { attack: 2900, defense: 900, health: 10200, speed: 410 },
    lore: "Karn raided every port on the coast until the ports simply started leaving out snacks. It worked, mostly.",
    unlocked: false,
    art: "/game/champions/karn-the-reaver.png",
  },
  {
    slug: "ser-brannoch",
    name: "Ser Brannoch",
    title: "The Loud Knight",
    rarity: "rare",
    house: "House Stormcrest",
    weapon: "Mace",
    weaponClass: "Bludgeon",
    passive: {
      name: "Booming Presence",
      desc: "Enemies adjacent to Brannoch suffer reduced accuracy, mostly from the ringing in their ears.",
    },
    ultimate: {
      name: "Warcry",
      desc: "Brannoch bellows a rallying roar, boosting the attack of every ally and stunning the nearest foe.",
    },
    stats: { attack: 1600, defense: 1100, health: 9500, speed: 360 },
    lore: "Brannoch has never won a battle of wits, but he has ended several by shouting over them.",
    unlocked: false,
    art: "/game/champions/ser-brannoch.png",
  },
  {
    slug: "nymeria-vale",
    name: "Nymeria Vale",
    title: "The Far-Reaching",
    rarity: "rare",
    house: "House Corvane",
    weapon: "Longbow",
    weaponClass: "Bow",
    passive: {
      name: "Hawk's Patience",
      desc: "Nymeria's damage increases for every turn she waits without attacking.",
    },
    ultimate: {
      name: "Volley",
      desc: "Nymeria looses a storm of arrows that rains on all enemies, striking the weakest twice.",
    },
    stats: { attack: 1900, defense: 550, health: 7500, speed: 440 },
    lore: "Nymeria once shot an apple off a moving cart at four hundred paces. The cart driver still writes her angry letters.",
    unlocked: false,
    art: "/game/champions/nymeria-vale.png",
  },
  {
    slug: "gwendal-frost",
    name: "Gwendal Frost",
    title: "The Winter's Lance",
    rarity: "epic",
    house: "House Frosthold",
    weapon: "Spear",
    weaponClass: "Polearm",
    passive: {
      name: "Chilling Reach",
      desc: "Gwendal's strikes slow enemies, reducing their speed with every hit.",
    },
    ultimate: {
      name: "Frostbite",
      desc: "Gwendal drives his spear into the ground, freezing all enemies in place and dealing damage over three turns.",
    },
    stats: { attack: 2400, defense: 1200, health: 10500, speed: 380 },
    lore: "Gwendal speaks four words a day and saves them for battle. His spear handles the rest of the conversation.",
    unlocked: false,
    art: "/game/champions/gwendal-frost.png",
  },
  {
    slug: "ser-aldric",
    name: "Ser Aldric",
    title: "The Burning Chain",
    rarity: "legendary",
    house: "House Emberfall",
    weapon: "Flail",
    weaponClass: "Bludgeon",
    passive: {
      name: "Kindled Fury",
      desc: "Each swing of Aldric's flail has a chance to ignite foes, burning them for extra damage each turn.",
    },
    ultimate: {
      name: "Wildfire",
      desc: "Aldric whirls his blazing flail in a great arc, setting the entire battlefield alight and scorching every enemy.",
    },
    stats: { attack: 3300, defense: 1250, health: 12000, speed: 420 },
    lore: "Aldric swore an oath by fire, which was dramatic right up until the fire took him at his word. Now they are inseparable.",
    unlocked: false,
    art: "/game/champions/ser-aldric.png",
  },
  {
    slug: "bael-the-bard",
    name: "Bael the Bard",
    title: "Voice of Velvet",
    rarity: "rare",
    house: "House Nightvale",
    weapon: "Dagger",
    weaponClass: "Blade",
    passive: {
      name: "Cutting Verse",
      desc: "Bael's mockery lowers the defense of whichever enemy he last struck.",
    },
    ultimate: {
      name: "Charm",
      desc: "Bael sings a song so persuasive that one enemy fights for his side for a full turn.",
    },
    stats: { attack: 1400, defense: 600, health: 7200, speed: 450 },
    lore: "Bael has talked his way out of six dungeons and into at least three thrones. He gave the thrones back. Probably.",
    unlocked: false,
    art: "/game/champions/bael-the-bard.png",
  },
  {
    slug: "sable-nightwood",
    name: "Sable Nightwood",
    title: "The Quiet Harvest",
    rarity: "epic",
    house: "House Nightvale",
    weapon: "War Scythe",
    weaponClass: "Polearm",
    passive: {
      name: "Gloom Veil",
      desc: "Sable becomes untargetable for one turn after landing a killing blow.",
    },
    ultimate: {
      name: "Shadowstep",
      desc: "Sable vanishes into shadow and reappears behind the enemy line, striking their weakest champion with lethal precision.",
    },
    stats: { attack: 2800, defense: 800, health: 9000, speed: 480 },
    lore: "Nobody has ever heard Sable arrive. A few have heard her leave, which is generally the last thing they hear.",
    unlocked: false,
    art: "/game/champions/sable-nightwood.png",
  },
  {
    slug: "grommash",
    name: "Grommash",
    title: "The Walking Rampart",
    rarity: "legendary",
    house: "House Frosthold",
    weapon: "Maul",
    weaponClass: "Bludgeon",
    passive: {
      name: "Unshakable",
      desc: "Grommash ignores the first debuff applied to him each battle.",
    },
    ultimate: {
      name: "Quake",
      desc: "Grommash slams his maul into the earth, splitting the ground and staggering every enemy for two turns.",
    },
    stats: { attack: 3200, defense: 1550, health: 13800, speed: 310 },
    lore: "Grommash once shouldered a collapsing gatehouse so his company could retreat. Then he put it back, because he hates mess.",
    unlocked: false,
    art: "/game/champions/grommash.png",
  },
  {
    slug: "ser-elyra",
    name: "Ser Elyra",
    title: "The Line That Holds",
    rarity: "rare",
    house: "House Goldmane",
    weapon: "Halberd",
    weaponClass: "Polearm",
    passive: {
      name: "Golden Guard",
      desc: "Elyra redirects a portion of damage from the ally with the lowest health to herself.",
    },
    ultimate: {
      name: "Bulwark",
      desc: "Elyra anchors the formation, granting every ally a shield that scales with her own defense.",
    },
    stats: { attack: 1550, defense: 1300, health: 10000, speed: 350 },
    lore: "Elyra was knighted for holding a breach alone for a full night. She calls it a quiet evening with good exercise.",
    unlocked: false,
    art: "/game/champions/ser-elyra.png",
  },
  {
    slug: "the-faceless",
    name: "The Faceless",
    title: "A Stranger to All",
    rarity: "mythic",
    house: "House Nightvale",
    weapon: "Needle",
    weaponClass: "Blade",
    passive: {
      name: "Borrowed Face",
      desc: "At the start of battle, The Faceless copies the passive of a random enemy champion.",
    },
    ultimate: {
      name: "No One",
      desc: "The Faceless sheds all identity, becoming immune to targeting while striking each enemy once from nowhere.",
    },
    stats: { attack: 3700, defense: 1100, health: 12800, speed: 500 },
    lore: "The Faceless has been a fishmonger, a queen, a beggar, and possibly you. If asked, The Faceless denies being anyone at all.",
    unlocked: false,
    art: "/game/champions/the-faceless.png",
  },
  {
    slug: "vorian-nightblade",
    name: "Vorian Nightblade",
    title: "Herald of the Long Dusk",
    rarity: "legendary",
    house: "House Nightvale",
    weapon: "Voidscythe",
    weaponClass: "Polearm",
    passive: {
      name: "Dusk Hunger",
      desc: "Vorian's scythe drinks light, gaining attack for every debuffed enemy on the field.",
    },
    ultimate: {
      name: "Eclipse Reaping",
      desc: "Vorian swings the Voidscythe through shadow itself, dealing damage that ignores all shields and armor.",
    },
    stats: { attack: 3500, defense: 1150, health: 12200, speed: 445 },
    lore: "Vorian found the Voidscythe in a place maps refuse to mention. The scythe insists it found him, and it usually wins arguments.",
    unlocked: false,
    art: "/game/champions/vorian-nightblade.png",
  },
  {
    slug: "kaelen-dragonborn",
    name: "Kaelen Dragonborn",
    title: "The Last Ember of the Old Fire",
    rarity: "mythic",
    house: "House Emberfall",
    weapon: "Dragonspine",
    weaponClass: "Greatsword",
    passive: {
      name: "Molten Blood",
      desc: "Kaelen heals each turn he stands in fire, and he is very good at standing in fire.",
    },
    ultimate: {
      name: "Ancestral Inferno",
      desc: "Kaelen calls down the breath of his ancient forebears, engulfing all enemies in dragonfire for massive damage.",
    },
    stats: { attack: 3800, defense: 1300, health: 13500, speed: 470 },
    lore: "Kaelen's family tree includes at least one actual dragon, a fact he mentions within forty seconds of any introduction.",
    unlocked: false,
    art: "/game/champions/kaelen-dragonborn.png",
  },
  {
    slug: "morrigan-shadowmist",
    name: "Morrigan Shadowmist",
    title: "The Whisper Between Walls",
    rarity: "epic",
    house: "House Nightvale",
    weapon: "Throwing Knives",
    weaponClass: "Thrown",
    passive: {
      name: "Misted Steps",
      desc: "Morrigan gains bonus speed after every attack she makes from stealth.",
    },
    ultimate: {
      name: "Thousand Cuts",
      desc: "Morrigan hurls a fan of knives from every shadow at once, striking all enemies and marking them for bonus damage.",
    },
    stats: { attack: 2600, defense: 700, health: 8800, speed: 490 },
    lore: "Morrigan owns ninety-nine knives and claims each has a name. Her enemies rarely stay long enough for introductions.",
    unlocked: false,
    art: "/game/champions/morrigan-shadowmist.png",
  },
  {
    slug: "dreven-the-crusher",
    name: "Dreven the Crusher",
    title: "Doom of Gates",
    rarity: "legendary",
    house: "House Emberfall",
    weapon: "Warhammer",
    weaponClass: "Bludgeon",
    passive: {
      name: "Demolisher",
      desc: "Dreven deals double damage to shields, barriers, and anything else optimistic enough to block him.",
    },
    ultimate: {
      name: "Gatebreaker",
      desc: "Dreven brings his hammer down with siege-engine force, shattering all enemy defenses and stunning the frontline.",
    },
    stats: { attack: 3600, defense: 1400, health: 13000, speed: 340 },
    lore: "Castles across the realm now build two gates, on the theory that Dreven only has time to crush one of them.",
    unlocked: false,
    art: "/game/champions/dreven-the-crusher.png",
  },
  {
    slug: "isolde-the-pure",
    name: "Isolde the Pure",
    title: "Light of the Seven Roads",
    rarity: "legendary",
    house: "House Goldmane",
    weapon: "Dawnbringer",
    weaponClass: "Greatsword",
    passive: {
      name: "Radiant Vow",
      desc: "Isolde heals her most wounded ally a little every time she lands a strike.",
    },
    ultimate: {
      name: "Daybreak Judgment",
      desc: "Isolde raises Dawnbringer to the sky, blinding all enemies and dealing holy damage that doubles against shadow.",
    },
    stats: { attack: 3300, defense: 1450, health: 12600, speed: 400 },
    lore: "Isolde took a vow to never lie, which makes her both the realm's finest knight and its most dreaded dinner guest.",
    unlocked: false,
    art: "/game/champions/isolde-the-pure.png",
  },
  {
    slug: "corvus-ashwing",
    name: "Corvus Ashwing",
    title: "The Raven Lord",
    rarity: "legendary",
    house: "House Corvane",
    weapon: "Obsidian Saber",
    weaponClass: "Blade",
    passive: {
      name: "Murder of Ravens",
      desc: "Corvus's ravens scout the field, revealing enemy weaknesses and boosting ally accuracy.",
    },
    ultimate: {
      name: "Wings of Ruin",
      desc: "A thousand ravens descend as a single black wave, tearing at every enemy and blinding them for a turn.",
    },
    stats: { attack: 3250, defense: 1200, health: 12100, speed: 455 },
    lore: "Corvus knows every secret in the realm because his ravens are terrible gossips. He pays them in shiny buttons.",
    unlocked: false,
  },
  {
    slug: "thessaly-quill",
    name: "Thessaly Quill",
    title: "Mistress of Whispers",
    rarity: "epic",
    house: "House Corvane",
    weapon: "Poison Stiletto",
    weaponClass: "Blade",
    passive: {
      name: "Ink and Venom",
      desc: "Thessaly's blade applies a poison that deepens each time the target acts.",
    },
    ultimate: {
      name: "Sealed Fate",
      desc: "Thessaly reveals a devastating secret, silencing one enemy's abilities for two full turns.",
    },
    stats: { attack: 2450, defense: 750, health: 8600, speed: 465 },
    lore: "Thessaly keeps a ledger of everyone's debts, favors, and embarrassments. Page one is blank, reserved, she says, for optimists.",
    unlocked: false,
  },
  {
    slug: "ser-oswic-crane",
    name: "Ser Oswic Crane",
    title: "The Patient Blade",
    rarity: "rare",
    house: "House Corvane",
    weapon: "Bastard Sword",
    weaponClass: "Blade",
    passive: {
      name: "Measured Strikes",
      desc: "Oswic's accuracy rises with every attack he lands in sequence.",
    },
    ultimate: {
      name: "Checkmate",
      desc: "Oswic executes a move planned twelve turns in advance, dealing damage that cannot miss or be reduced.",
    },
    stats: { attack: 1750, defense: 950, health: 8900, speed: 395 },
    lore: "Oswic plans his duels like chess and his chess like duels. Nobody enjoys playing either with him.",
    unlocked: false,
  },
  {
    slug: "ravenna-holt",
    name: "Ravenna Holt",
    title: "Keeper of the Black Archive",
    rarity: "epic",
    house: "House Corvane",
    weapon: "Runed Staff",
    weaponClass: "Staff",
    passive: {
      name: "Forbidden Footnotes",
      desc: "Ravenna counters enemy magic with a citation, reducing all incoming spell damage.",
    },
    ultimate: {
      name: "The Unwritten Page",
      desc: "Ravenna rewrites one moment of the battle, undoing the last damage dealt to her allies.",
    },
    stats: { attack: 2300, defense: 1000, health: 9600, speed: 405 },
    lore: "Ravenna has read every book in the Black Archive, including the ones that read back. They correspond regularly.",
    unlocked: false,
  },
  {
    slug: "finch-the-younger",
    name: "Finch the Younger",
    title: "The Lockpick of Legends",
    rarity: "rare",
    house: "House Corvane",
    weapon: "Hooked Blades",
    weaponClass: "Dual Blade",
    passive: {
      name: "Sticky Fingers",
      desc: "Finch steals a small buff from any enemy he strikes.",
    },
    ultimate: {
      name: "Grand Heist",
      desc: "Finch pilfers every active enemy buff at once and distributes them among his allies.",
    },
    stats: { attack: 1650, defense: 650, health: 7800, speed: 470 },
    lore: "Finch once stole the crown, the throne, and the argument for keeping either. He returned them all, plus interest, in embarrassment.",
    unlocked: false,
  },
  {
    slug: "maren-darkfeather",
    name: "Maren Darkfeather",
    title: "The Owl at Midnight",
    rarity: "rare",
    house: "House Corvane",
    weapon: "Recurve Bow",
    weaponClass: "Bow",
    passive: {
      name: "Night Vision",
      desc: "Maren ignores all accuracy penalties and dodges better in the dark.",
    },
    ultimate: {
      name: "Silent Feather",
      desc: "Maren fires a single soundless arrow that always strikes the enemy with the highest attack.",
    },
    stats: { attack: 1850, defense: 600, health: 7600, speed: 475 },
    lore: "Maren speaks softly and shoots quieter. Most of her targets assume the arrow was a very sudden idea.",
    unlocked: false,
  },
  {
    slug: "lucan-vayle",
    name: "Lucan Vayle",
    title: "The Gilded Tongue",
    rarity: "legendary",
    house: "House Corvane",
    weapon: "Cane Sword",
    weaponClass: "Blade",
    passive: {
      name: "Silver Words",
      desc: "Lucan talks one enemy per battle into skipping their first turn entirely.",
    },
    ultimate: {
      name: "The Long Con",
      desc: "Lucan springs a trap laid before the battle began, dealing massive damage to the entire enemy line.",
    },
    stats: { attack: 3100, defense: 1250, health: 11900, speed: 435 },
    lore: "Lucan sold a bridge to the man who built it, twice. The realm's merchants now negotiate with him by letter, from far away.",
    unlocked: false,
  },
  {
    slug: "pyrra-flameheart",
    name: "Pyrra Flameheart",
    title: "The First Spark",
    rarity: "legendary",
    house: "House Emberfall",
    weapon: "Flame Whip",
    weaponClass: "Whip",
    passive: {
      name: "Ever Burning",
      desc: "Pyrra's attacks leave embers that reignite whenever the target is healed.",
    },
    ultimate: {
      name: "Phoenix Lash",
      desc: "Pyrra's whip becomes a ribbon of living fire, striking all enemies and reviving her own health from the ashes.",
    },
    stats: { attack: 3350, defense: 1100, health: 11700, speed: 460 },
    lore: "Pyrra lights the great beacons of Emberfall with a snap of her fingers, mostly because matches bore her.",
    unlocked: false,
  },
  {
    slug: "ser-caldus-brand",
    name: "Ser Caldus Brand",
    title: "Knight of the Cinder Road",
    rarity: "epic",
    house: "House Emberfall",
    weapon: "Burning Lance",
    weaponClass: "Polearm",
    passive: {
      name: "Scorched Trail",
      desc: "Caldus leaves a line of fire behind his charges that burns pursuing enemies.",
    },
    ultimate: {
      name: "Comet Charge",
      desc: "Caldus charges through the enemy formation like a falling star, damaging everyone in his path.",
    },
    stats: { attack: 2650, defense: 1050, health: 10100, speed: 425 },
    lore: "Caldus has never lost a joust, partly through skill and partly because his lance is on fire and horses have opinions about that.",
    unlocked: false,
  },
  {
    slug: "ashka-emberveil",
    name: "Ashka Emberveil",
    title: "The Smoke Dancer",
    rarity: "epic",
    house: "House Emberfall",
    weapon: "Chakrams",
    weaponClass: "Thrown",
    passive: {
      name: "Smokescreen",
      desc: "Ashka's movements kick up ash, reducing enemy accuracy against her.",
    },
    ultimate: {
      name: "Ring of Cinders",
      desc: "Ashka's chakrams orbit the battlefield in flame, slicing every enemy twice before returning to her hands.",
    },
    stats: { attack: 2550, defense: 800, health: 9100, speed: 485 },
    lore: "Ashka learned to dance in the festival fires of the south. Her performances are unforgettable and mildly hazardous.",
    unlocked: false,
  },
  {
    slug: "brom-coalbeard",
    name: "Brom Coalbeard",
    title: "The Forge Father",
    rarity: "rare",
    house: "House Emberfall",
    weapon: "Smithing Hammer",
    weaponClass: "Bludgeon",
    passive: {
      name: "Field Repairs",
      desc: "Brom mends ally armor between turns, restoring a sliver of their defense.",
    },
    ultimate: {
      name: "Masterwork",
      desc: "Brom reforges an ally's weapon mid-battle, greatly boosting their attack for the rest of the fight.",
    },
    stats: { attack: 1500, defense: 1150, health: 9800, speed: 335 },
    lore: "Brom forged half the famous blades in the realm and complains loudly about how the other half were made.",
    unlocked: false,
  },
  {
    slug: "seraphine-dawnash",
    name: "Seraphine Dawnash",
    title: "The Morning Flame",
    rarity: "rare",
    house: "House Emberfall",
    weapon: "Torch Staff",
    weaponClass: "Staff",
    passive: {
      name: "Warm Glow",
      desc: "Allies near Seraphine regenerate a small amount of health each turn.",
    },
    ultimate: {
      name: "Sunrise",
      desc: "Seraphine floods the field with dawn light, healing all allies and burning away enemy shadows.",
    },
    stats: { attack: 1450, defense: 850, health: 8700, speed: 415 },
    lore: "Seraphine rises before the sun out of professional courtesy. The sun, to its credit, has never once beaten her to it.",
    unlocked: false,
  },
  {
    slug: "varek-hollowflame",
    name: "Varek Hollowflame",
    title: "The Ash King's Heir",
    rarity: "legendary",
    house: "House Emberfall",
    weapon: "Ember Greatsword",
    weaponClass: "Greatsword",
    passive: {
      name: "Funeral Pyre",
      desc: "When an ally falls, Varek's blade absorbs their fire, permanently gaining attack.",
    },
    ultimate: {
      name: "Kingdom of Ash",
      desc: "Varek unleashes generations of stored flame in one blow, dealing colossal damage to a single enemy.",
    },
    stats: { attack: 3550, defense: 1300, health: 12400, speed: 390 },
    lore: "Varek carries the last ember of a burned kingdom in his sword's hilt. He is saving it for something, and no one asks what.",
    unlocked: false,
  },
  {
    slug: "roderic-tallow",
    name: "Roderic Tallow",
    title: "The Candle Knight",
    rarity: "rare",
    house: "House Emberfall",
    weapon: "Short Sword",
    weaponClass: "Blade",
    passive: {
      name: "Slow Burn",
      desc: "Roderic's attack grows steadily the longer the battle lasts.",
    },
    ultimate: {
      name: "Final Flicker",
      desc: "Roderic burns brightest at the end, dealing damage proportional to the health he has lost.",
    },
    stats: { attack: 1600, defense: 900, health: 9300, speed: 370 },
    lore: "Roderic is unremarkable for the first hour of any battle and legendary in the last five minutes. Plan accordingly.",
    unlocked: false,
  },
  {
    slug: "helga-winterborn",
    name: "Helga Winterborn",
    title: "The Glacier's Daughter",
    rarity: "legendary",
    house: "House Frosthold",
    weapon: "Ice Greataxe",
    weaponClass: "Axe",
    passive: {
      name: "Permafrost Skin",
      desc: "Helga takes reduced damage from every attack after the first each turn.",
    },
    ultimate: {
      name: "Avalanche Call",
      desc: "Helga summons a wall of falling ice that crushes the enemy frontline and buries their speed.",
    },
    stats: { attack: 3150, defense: 1500, health: 13200, speed: 325 },
    lore: "Helga swims in frozen lakes for fun and describes blizzards as refreshing. Her enemies find her exactly as pleasant.",
    unlocked: false,
  },
  {
    slug: "ser-jorund-pale",
    name: "Ser Jorund Pale",
    title: "The Sentinel of the White Pass",
    rarity: "epic",
    house: "House Frosthold",
    weapon: "Tower Shield and Sword",
    weaponClass: "Sword and Shield",
    passive: {
      name: "Watchful Stand",
      desc: "Jorund intercepts the first attack aimed at any ally each turn.",
    },
    ultimate: {
      name: "The Pass Holds",
      desc: "Jorund becomes an immovable wall, taunting all enemies and taking half damage for two turns.",
    },
    stats: { attack: 2200, defense: 1550, health: 11500, speed: 315 },
    lore: "Jorund has guarded the White Pass for twenty years. Nothing has gotten through, including, famously, one very determined goat.",
    unlocked: false,
  },
  {
    slug: "eira-coldsong",
    name: "Eira Coldsong",
    title: "The Voice of the North Wind",
    rarity: "epic",
    house: "House Frosthold",
    weapon: "Frost Harp",
    weaponClass: "Instrument",
    passive: {
      name: "Lullaby of Sleet",
      desc: "Eira's music slows all enemies slightly at the start of each turn.",
    },
    ultimate: {
      name: "Winter's Dirge",
      desc: "Eira plays a song of deep winter, freezing enemy buffs solid and shattering them.",
    },
    stats: { attack: 2350, defense: 950, health: 9700, speed: 400 },
    lore: "Eira's songs can quiet a storm or start a war, depending on the requests. She takes requests. She does not take criticism.",
    unlocked: false,
  },
  {
    slug: "bjorn-frostfell",
    name: "Bjorn Frostfell",
    title: "The Bear of the Tundra",
    rarity: "rare",
    house: "House Frosthold",
    weapon: "Twin Axes",
    weaponClass: "Axe",
    passive: {
      name: "Thick Pelt",
      desc: "Bjorn shrugs off the first status effect applied to him each battle.",
    },
    ultimate: {
      name: "Hibernation's End",
      desc: "Bjorn erupts in fury, gaining massive attack and striking every adjacent enemy.",
    },
    stats: { attack: 1800, defense: 1050, health: 10400, speed: 345 },
    lore: "Bjorn wrestled a bear once, and they have been fishing partners ever since. The bear tells the story better.",
    unlocked: false,
  },
  {
    slug: "sigrid-hoarfrost",
    name: "Sigrid Hoarfrost",
    title: "The Ice-Eyed",
    rarity: "rare",
    house: "House Frosthold",
    weapon: "Crossbow",
    weaponClass: "Crossbow",
    passive: {
      name: "Steady Breath",
      desc: "Sigrid's first shot each battle is always a critical hit.",
    },
    ultimate: {
      name: "Glacier Bolt",
      desc: "Sigrid fires a bolt of compressed ice that pierces the entire enemy line, freezing whoever it stops in.",
    },
    stats: { attack: 1900, defense: 700, health: 8200, speed: 385 },
    lore: "Sigrid can wait in a snowbank for three days for one perfect shot. Her patience is famous, her targets less so.",
    unlocked: false,
  },
  {
    slug: "ulfar-the-stalwart",
    name: "Ulfar the Stalwart",
    title: "The Last to Fall",
    rarity: "legendary",
    house: "House Frosthold",
    weapon: "Frostbrand Claymore",
    weaponClass: "Greatsword",
    passive: {
      name: "Deathless Winter",
      desc: "The first time Ulfar would fall each battle, he survives with one health and frozen resolve.",
    },
    ultimate: {
      name: "Stand of the Ancients",
      desc: "Ulfar channels the endurance of every ancestor, becoming invulnerable for a turn while counterattacking all foes.",
    },
    stats: { attack: 3050, defense: 1600, health: 14000, speed: 305 },
    lore: "Ulfar has been declared dead four times and attended two of his own funerals. He brought snacks and mild corrections.",
    unlocked: false,
  },
  {
    slug: "tempest-kael",
    name: "Tempest Kael",
    title: "The Rider of Gales",
    rarity: "legendary",
    house: "House Stormcrest",
    weapon: "Storm Glaive",
    weaponClass: "Polearm",
    passive: {
      name: "Tailwind",
      desc: "Kael always acts first in battle, and his speed rises after every dodge.",
    },
    ultimate: {
      name: "Eye of the Hurricane",
      desc: "Kael spins his glaive into a cyclone, pulling all enemies together and striking them as one.",
    },
    stats: { attack: 3200, defense: 1050, health: 11600, speed: 500 },
    lore: "Kael raced the wind across the Bone Cliffs and won by a nose. The wind demanded a rematch. It is still pending.",
    unlocked: false,
  },
  {
    slug: "wren-galecaller",
    name: "Wren Galecaller",
    title: "The Sky's Herald",
    rarity: "epic",
    house: "House Stormcrest",
    weapon: "Wind Staff",
    weaponClass: "Staff",
    passive: {
      name: "Uplift",
      desc: "Wren's winds grant a random ally bonus speed each turn.",
    },
    ultimate: {
      name: "Sky Split",
      desc: "Wren tears the clouds open, calling three bolts of lightning down on the three strongest enemies.",
    },
    stats: { attack: 2500, defense: 850, health: 9400, speed: 490 },
    lore: "Wren whistles and the weather listens, mostly. The exception was one memorable picnic that Stormcrest does not discuss.",
    unlocked: false,
  },
  {
    slug: "ser-darrow-swift",
    name: "Ser Darrow Swift",
    title: "The Knight of Nine Winds",
    rarity: "rare",
    house: "House Stormcrest",
    weapon: "Saber",
    weaponClass: "Blade",
    passive: {
      name: "Quickdraw",
      desc: "Darrow counterattacks any enemy slower than him who strikes first.",
    },
    ultimate: {
      name: "Nine Cuts",
      desc: "Darrow delivers nine strikes in the space of one, each faster and harder than the last.",
    },
    stats: { attack: 1850, defense: 750, health: 8400, speed: 480 },
    lore: "Darrow's duels end so quickly that spectators demand refunds. He now sells tickets by the second, at a discount.",
    unlocked: false,
  },
  {
    slug: "petra-boneweather",
    name: "Petra Boneweather",
    title: "The Storm Reader",
    rarity: "rare",
    house: "House Stormcrest",
    weapon: "Bone Darts",
    weaponClass: "Thrown",
    passive: {
      name: "Pressure Drop",
      desc: "Petra senses attacks a heartbeat early, granting her a chance to evade completely.",
    },
    ultimate: {
      name: "Forecast of Ruin",
      desc: "Petra predicts every enemy move for a turn, causing all their attacks to miss her allies.",
    },
    stats: { attack: 1700, defense: 650, health: 7900, speed: 495 },
    lore: "Petra reads storms in old bones and has never been wrong, only, as she puts it, early. Sometimes by several years.",
    unlocked: false,
  },
  {
    slug: "cormac-thunderhide",
    name: "Cormac Thunderhide",
    title: "The Rolling Boom",
    rarity: "epic",
    house: "House Stormcrest",
    weapon: "Stormdrum Gauntlets",
    weaponClass: "Fist",
    passive: {
      name: "Static Buildup",
      desc: "Every hit Cormac takes charges his gauntlets, empowering his next punch.",
    },
    ultimate: {
      name: "Thunderclap",
      desc: "Cormac slams his gauntlets together, releasing a shockwave that deafens and damages all enemies.",
    },
    stats: { attack: 2750, defense: 1100, health: 10600, speed: 420 },
    lore: "Cormac's handshake has been outlawed in three provinces. He considers this a compliment and shakes hands anyway.",
    unlocked: false,
  },
  {
    slug: "lyra-windmere",
    name: "Lyra Windmere",
    title: "The Falcon of the Crest",
    rarity: "legendary",
    house: "House Stormcrest",
    weapon: "Twin Storm Sabers",
    weaponClass: "Dual Blade",
    passive: {
      name: "Dive Strike",
      desc: "Lyra deals bonus damage to any enemy who has not yet acted this turn.",
    },
    ultimate: {
      name: "Falcon's Descent",
      desc: "Lyra strikes from above like a diving raptor, hitting one enemy with unavoidable, armor-shredding force.",
    },
    stats: { attack: 3300, defense: 1000, health: 11300, speed: 500 },
    lore: "Lyra was raised alongside the falcons of the high crags and learned their two great lessons, strike first and never apologize to a pigeon.",
    unlocked: false,
  },
  {
    slug: "umbra-veilwalker",
    name: "Umbra Veilwalker",
    title: "The Space Between Shadows",
    rarity: "legendary",
    house: "House Nightvale",
    weapon: "Shadow Blades",
    weaponClass: "Dual Blade",
    passive: {
      name: "Half Here",
      desc: "Umbra exists partly in shadow, giving every attack against her a chance to pass through nothing.",
    },
    ultimate: {
      name: "Veil Collapse",
      desc: "Umbra drags the whole battlefield into darkness, striking every enemy from angles that should not exist.",
    },
    stats: { attack: 3400, defense: 1050, health: 11800, speed: 495 },
    lore: "Umbra's shadow arrives places before she does and reports back. They disagree occasionally, which is unsettling for everyone nearby.",
    unlocked: false,
  },
  {
    slug: "ser-mordane",
    name: "Ser Mordane",
    title: "The Knight of Unspoken Oaths",
    rarity: "legendary",
    house: "House Nightvale",
    weapon: "Black Longsword",
    weaponClass: "Blade",
    passive: {
      name: "Grim Silence",
      desc: "Mordane's presence unnerves enemies, lowering the attack of any foe who targets him.",
    },
    ultimate: {
      name: "Oathkeeper's Toll",
      desc: "Mordane exacts the price of every broken promise, dealing damage that grows with each enemy buff.",
    },
    stats: { attack: 3100, defense: 1250, health: 12300, speed: 410 },
    lore: "Mordane swore an oath so secret even he will not say what it was. He keeps it anyway, meticulously, at midnight.",
    unlocked: false,
  },
  {
    slug: "nyx-emberdim",
    name: "Nyx Emberdim",
    title: "The Last Candle",
    rarity: "rare",
    house: "House Nightvale",
    weapon: "Hooked Chain",
    weaponClass: "Whip",
    passive: {
      name: "Dim the Lights",
      desc: "Nyx snuffs one random enemy buff at the start of each battle.",
    },
    ultimate: {
      name: "Lights Out",
      desc: "Nyx plunges the field into blackness, causing all enemy attacks to miss for one turn.",
    },
    stats: { attack: 1600, defense: 700, health: 8100, speed: 455 },
    lore: "Nyx collects candle stubs from every place she has infiltrated. Her collection is enormous and deeply incriminating.",
    unlocked: false,
  },
  {
    slug: "silas-duskbane",
    name: "Silas Duskbane",
    title: "The Cartographer of Nowhere",
    rarity: "rare",
    house: "House Nightvale",
    weapon: "Curved Daggers",
    weaponClass: "Dual Blade",
    passive: {
      name: "Off the Map",
      desc: "Silas cannot be targeted by abilities that select the weakest champion.",
    },
    ultimate: {
      name: "Uncharted Strike",
      desc: "Silas attacks from a place no map records, dealing damage that ignores positioning entirely.",
    },
    stats: { attack: 1800, defense: 600, health: 7700, speed: 485 },
    lore: "Silas maps the places that do not want to be found. The places have filed several complaints, all of which got lost.",
    unlocked: false,
  },
  {
    slug: "vespera-crow",
    name: "Vespera Crow",
    title: "The Evening Star",
    rarity: "epic",
    house: "House Nightvale",
    weapon: "Void Bow",
    weaponClass: "Bow",
    passive: {
      name: "Twilight Aim",
      desc: "Vespera's arrows curve through shadow, unable to be blocked by frontline champions.",
    },
    ultimate: {
      name: "Starfall Shot",
      desc: "Vespera fires an arrow into the void that returns from above as a rain of dark light on all enemies.",
    },
    stats: { attack: 2700, defense: 700, health: 9000, speed: 470 },
    lore: "Vespera only appears at dusk, which makes scheduling difficult and ambushes extremely punctual.",
    unlocked: false,
  },
  {
    slug: "leonar-goldmane",
    name: "Leonar Goldmane",
    title: "The Lion Ascendant",
    rarity: "legendary",
    house: "House Goldmane",
    weapon: "Lion's Claw Greatsword",
    weaponClass: "Greatsword",
    passive: {
      name: "Pride's Roar",
      desc: "Leonar's allies gain attack whenever he lands a critical hit.",
    },
    ultimate: {
      name: "Golden Dominion",
      desc: "Leonar claims the field as his own, dealing massive damage to all enemies and crowning himself with a damage shield.",
    },
    stats: { attack: 3450, defense: 1350, health: 12700, speed: 415 },
    lore: "Leonar has never lost, according to Leonar. The record keepers agree, mostly because he pays the record keepers.",
    unlocked: false,
  },
  {
    slug: "octavia-gilt",
    name: "Octavia Gilt",
    title: "The Coin Countess",
    rarity: "epic",
    house: "House Goldmane",
    weapon: "Coin-Edged Fans",
    weaponClass: "Thrown",
    passive: {
      name: "Compound Interest",
      desc: "Octavia's damage grows a little every turn, and she always collects.",
    },
    ultimate: {
      name: "Market Crash",
      desc: "Octavia calls in every debt at once, stripping all enemy shields and converting them into damage.",
    },
    stats: { attack: 2450, defense: 900, health: 9500, speed: 440 },
    lore: "Octavia never carries a weapon into negotiations. Technically the fans are accounting equipment, and her ledgers agree.",
    unlocked: false,
  },
  {
    slug: "ser-percival-vane",
    name: "Ser Percival Vane",
    title: "The Mirror Knight",
    rarity: "epic",
    house: "House Goldmane",
    weapon: "Polished Greatshield",
    weaponClass: "Sword and Shield",
    passive: {
      name: "Dazzling Sheen",
      desc: "Percival's mirrored armor reflects a portion of all magic damage back at the caster.",
    },
    ultimate: {
      name: "Blinding Glory",
      desc: "Percival angles his shield to the sun, blinding all enemies and reducing their accuracy for two turns.",
    },
    stats: { attack: 2250, defense: 1500, health: 11200, speed: 355 },
    lore: "Percival polishes his armor for three hours daily. His enemies see themselves in it, which he insists is the point.",
    unlocked: false,
  },
  {
    slug: "magnus-aurelian",
    name: "Magnus Aurelian",
    title: "The Vaultbreaker",
    rarity: "legendary",
    house: "House Goldmane",
    weapon: "Gilded Maul",
    weaponClass: "Bludgeon",
    passive: {
      name: "Heavy Purse",
      desc: "Magnus hits harder for every buff his team holds, because wealth compounds.",
    },
    ultimate: {
      name: "King's Ransom",
      desc: "Magnus delivers a blow worth a kingdom, dealing single-target damage that scales with his remaining health.",
    },
    stats: { attack: 3500, defense: 1400, health: 13100, speed: 350 },
    lore: "Magnus broke into the realm's grandest vault just to prove he could, then left a donation. The bank framed his apology note.",
    unlocked: false,
  },
  {
    slug: "cressida-lorne",
    name: "Cressida Lorne",
    title: "The Velvet Verdict",
    rarity: "rare",
    house: "House Goldmane",
    weapon: "Scepter",
    weaponClass: "Staff",
    passive: {
      name: "Court Ruling",
      desc: "Cressida overrules one enemy buff per battle, dismissing it entirely.",
    },
    ultimate: {
      name: "Final Judgment",
      desc: "Cressida passes sentence on the strongest enemy, halving their attack for the rest of the battle.",
    },
    stats: { attack: 1500, defense: 950, health: 8600, speed: 390 },
    lore: "Cressida has judged dukes, generals, and one extremely guilty goose. Her verdicts are famously fair and terrifyingly final.",
    unlocked: false,
  },
  {
    slug: "hadrian-voss",
    name: "Hadrian Voss",
    title: "The Auction Master",
    rarity: "epic",
    house: "House Goldmane",
    weapon: "Gavel Hammer",
    weaponClass: "Bludgeon",
    passive: {
      name: "Going Once",
      desc: "Hadrian's first strike against each enemy deals bonus opening-bid damage.",
    },
    ultimate: {
      name: "Sold to the Gentleman",
      desc: "Hadrian slams his gavel, dealing heavy damage and transferring one enemy buff to his own team.",
    },
    stats: { attack: 2400, defense: 1000, health: 9900, speed: 395 },
    lore: "Hadrian once auctioned a castle while it was under siege, twice, to both sides. The margins were spectacular.",
    unlocked: false,
  },
  {
    slug: "elowen-brightshield",
    name: "Elowen Brightshield",
    title: "The Dawn Sentinel",
    rarity: "epic",
    house: "House Goldmane",
    weapon: "Sunforged Spear",
    weaponClass: "Polearm",
    passive: {
      name: "First Light",
      desc: "Elowen's opening attack each battle also heals her most wounded ally.",
    },
    ultimate: {
      name: "Radiant Phalanx",
      desc: "Elowen calls a formation of light, granting all allies shields and boosting their next attack.",
    },
    stats: { attack: 2300, defense: 1250, health: 10700, speed: 405 },
    lore: "Elowen guards the eastern gate at sunrise so the first thing invaders see is her, backlit and unimpressed.",
    unlocked: false,
  },
  {
    slug: "fenwick-mothbane",
    name: "Fenwick Mothbane",
    title: "The Lantern Keeper",
    rarity: "rare",
    house: "House Nightvale",
    weapon: "Lantern Flail",
    weaponClass: "Bludgeon",
    passive: {
      name: "Moth to Flame",
      desc: "Fenwick's lantern lures enemy attacks to himself, protecting his back line.",
    },
    ultimate: {
      name: "Lantern Burst",
      desc: "Fenwick's lantern erupts in trapped light, damaging and disorienting all nearby enemies.",
    },
    stats: { attack: 1550, defense: 1000, health: 9200, speed: 365 },
    lore: "Fenwick keeps the only lit lantern in Nightvale, which makes him either the bravest man there or the worst at stealth.",
    unlocked: false,
  },
  {
    slug: "orin-blackbriar",
    name: "Orin Blackbriar",
    title: "The Thorn Warden",
    rarity: "epic",
    house: "House Corvane",
    weapon: "Briar Whip",
    weaponClass: "Whip",
    passive: {
      name: "Tangled Ground",
      desc: "Enemies who move toward Orin take thorn damage on arrival.",
    },
    ultimate: {
      name: "Strangling Grove",
      desc: "Orin summons a wall of black briars that binds all enemies, dealing damage each turn they struggle.",
    },
    stats: { attack: 2350, defense: 1050, health: 9800, speed: 400 },
    lore: "Orin planted a hedge maze around his tower forty years ago. Tax collectors enter regularly. None have reached the door.",
    unlocked: false,
  },
  {
    slug: "runa-stormveil",
    name: "Runa Stormveil",
    title: "The Lightning Scribe",
    rarity: "legendary",
    house: "House Stormcrest",
    weapon: "Storm-Etched Runeblade",
    weaponClass: "Blade",
    passive: {
      name: "Charged Script",
      desc: "Runa inscribes a rune with each strike, and three runes trigger a free lightning bolt.",
    },
    ultimate: {
      name: "Verdict of the Sky",
      desc: "Runa completes her grand inscription, calling a pillar of lightning that devastates the chosen enemy.",
    },
    stats: { attack: 3250, defense: 1150, health: 12000, speed: 475 },
    lore: "Runa writes her battle plans in lightning across the clouds, which is dramatic, effective, and impossible for enemies to miss.",
    unlocked: false,
  },
  {
    slug: "godfrey-the-gray",
    name: "Godfrey the Gray",
    title: "The Retired Legend",
    rarity: "legendary",
    house: "House Frosthold",
    weapon: "Old Reliable Bastard Sword",
    weaponClass: "Blade",
    passive: {
      name: "Seen It All",
      desc: "Godfrey takes reduced damage from any ability he has already been hit with this battle.",
    },
    ultimate: {
      name: "One Last Lesson",
      desc: "Godfrey demonstrates the oldest trick in the book, a strike so fundamental it cannot be dodged, blocked, or argued with.",
    },
    stats: { attack: 3000, defense: 1450, health: 12900, speed: 360 },
    lore: "Godfrey retired three times and was un-retired by three separate wars. He now refuses to buy a rocking chair on principle.",
    unlocked: false,
  },
];
